---
info:
  title: Horses and Hussars
  description: Demo app for dev of grape swagger 2.0
  version: v1
swagger: '2.0'
produces:
- application/json
host: localhost:9292
tags:
- name: splines
  description: Operations about splines
- name: file
  description: Operations about files
schemes:
- https
- http
paths:
  "/splines":
    get:
      produces:
      - application/json
      responses:
        '200':
          description: get Splines
          schema:
            type: array
            items:
              "$ref": "#/definitions/Splines"
        '422':
          description: SplinesOutError
      tags:
      - splines
      operationId: getSplines
    post:
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - in: formData
        name: spline[x]
        description: 
        type: number
        required: true
        allowMultiple: false
        format: double
      - in: formData
        name: spline[y]
        description: 
        type: number
        required: true
        allowMultiple: false
        format: double
      - in: formData
        name: reticulated
        description: True if the spline is reticulated.
        type: boolean
        required: false
        allowMultiple: false
        defaultValue: true
      responses:
        '201':
          description: Spline created
          schema:
            "$ref": "#/definitions/Splines"
      tags:
      - splines
      operationId: postSplines
  "/splines/{id}":
    get:
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: Spline id.
        type: integer
        required: true
        allowMultiple: false
        format: int32
      responses:
        '200':
          description: get Splines
        '422':
          description: SplinesOutError
      tags:
      - splines
      operationId: getSplinesId
    put:
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - in: path
        name: id
        description: Spline id.
        type: integer
        required: true
        allowMultiple: false
        format: int32
      - in: formData
        name: spline[x]
        description: 
        type: number
        required: false
        allowMultiple: false
        format: double
      - in: formData
        name: spline[y]
        description: 
        type: number
        required: false
        allowMultiple: false
        format: double
      - in: formData
        name: reticulated
        description: True if the spline is reticulated.
        type: boolean
        required: false
        allowMultiple: false
        defaultValue: true
      responses:
        '200':
          description: update Splines
          schema:
            "$ref": "#/definitions/Splines"
        '422':
          description: SplinesOutError
      tags:
      - splines
      operationId: putSplinesId
    delete:
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: Spline id.
        type: integer
        required: true
        allowMultiple: false
        format: int32
      responses:
        '200':
          description: Delete a spline.
      tags:
      - splines
      operationId: deleteSplinesId
  "/file/upload":
    post:
      produces:
      - application/json
      consumes:
      - application/json
      responses:
        '201':
          description: Update image
      tags:
      - file
      operationId: postFileUpload
definitions:
  Splines:
    type: object
    properties:
      id:
        type: integer
      x:
        type: float
      y:
        type: float
      path:
        type: string
